DROP TABLE IF EXISTS member CASCADE ;
--generated by default as identity , 값 없이 insert 하면 자동으로 id를 채워줌

CREATE TABLE member (
   id bigint generated by default as identity,
   name varchar(255),
   PRIMARY KEY (id)
);