Spring :
  datasource :
    #url : jdbc:h2:tcp:localhost/~/jpashop;MVCC=TRUE
    url : jdbc:h2:tcp:localhost/~/jpashop; #mvcc ??? ?? ?? ??? ???
    username : sa
    password :
    driver-class-name : org.h2.Driver

  jpa :
    hibernate:
      ddl-auto: create
      #ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 9090
logging.level:
    org.hibernate.sql : debug
#    org.hibernate.type : trace #??? ??? ???? ????
