spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url:  jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
  sql :
    init :
      mode : always
      encoding: utf-8
mybatis:
  configuration:
    map-underscore-to-camel-case: true

server :
  port : 8080
